server:
  port: 9527
spring:
  application:
    name: springboot-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 20
    maxActive: 100
    minIdle: 10
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://23.254.136.61:3306/my_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

#配置mapper文件，及实体类的路径
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.example.springbootmybatis.dao.model
  configuration:
    map-underscore-to-camel-case: true

#控制台打印sql语句
logging:
    level:
      com.example.springbootmybatis.dao.mapper: DEBUG

